version: "3" 

volumes:
        web:

services:
        web-hello:
                build: web_app/
                restart: always
                ports:
                        - 8080:8080
                environment:
                        - TZ=Europe/Kiev
